volumes:
  pg_data:
  static:
  media:
  data: 
    external: false  


services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: xodyl/foodgram_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend_static
      - media:/app/media
      - data:/app/data
  frontend:
    image: xodyl/foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /static/
    depends_on:
      - backend
    volumes:
    - static:/static
  gateway:
    image: xodyl/foodgram_gateway
    env_file: .env
    ports:
      - 8000:80
    volumes:
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static:/static/
      - media:/app/media/
    depends_on:
      - backend
    restart: always

